apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: webapp1
  replicas: 1
  template:
    spec:
      containers:
        - name: webapp1
          image: webapp1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              
---

apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: "LoadBalancer"
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    name: blog